sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build main.tex

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  file: 'vrx_cv.pdf'
  on:
      repo: vrx-/vrx-.github.io/files
